### ISSUE TITLE
TP 1 - Babi

### ISSUE THREAD

**Issue by charlesbabi** [PYLP-UNaM/PYLP#107]
- [x] #133 Ejercicio 1

- [x] #29 Ejercicio 2

- [x] #31 Ejercicio 3

- [x] #105  Ejercicio 4

- [x] #134  Ejercicio 5

**Comment by SuichiM** [comment]
Estimado @charlesbabi ! no debe marcar como tildados las tareas de este epic de manera manual. 

la lista de tarea se ira chequeando automanticamente a medida de que desde la catedra se vayan integrando/cerrando PR correspondientes de los ejercicios particulares.

cualquier consulta, puede revisar el video de la clase 2 de practica, o publicar en el foro general de la materia en el moodle.
