### ISSUE TITLE
Review Zarske Firebase Aplication

### ISSUE THREAD

**Issue by charlesbabi** [PYLP-UNaM/PYLP#392]
## Registrar usuario
 
 * [x]  Funciona ✅
 
 * [ ]  No funciona ❌
 
 
 ## Login de usuario
 
* [x]  Funciona ✅
 
* [ ]  No funciona ❌
 
 
 ## Pagina de Usuarios
 
* [x]  Listado _(Se actualiza en tiempo real)_
 
* [x]  Alta
 
* [x]  Modificacion
 
* [x]  Eliminacion
 
 
 ## Pagina de Productos
 
* [x]  Listado _(Se actualiza en tiempo real)_
 
* [x]  Alta
 
* [x]  Modificacion
 
* [x]  Eliminacion

**Comment by SuichiM** [comment]
@charlesbabi  esta plantilla la debes usar para el registrar el test que te toco a vos. la de tu aplicacion la va a hacer tu compañero. el link de tu aplicacion pegala en el aula en el hilo que corresponde.

**Comment by charlesbabi** [comment]
aplicación finalizada
