### ISSUE TITLE
TP 1 - Villar

### ISSUE THREAD

**Issue by InahoAZ** [PYLP-UNaM/PYLP#47]
- [x] #40 Ejercicio 1

- [x] #60 Ejercicio 2 

- [x] #63 Ejercicio 3

- [x] #67 Ejercicio 4

- [x] #85 Ejercicio 5

**Comment by SuichiM** [comment]
Estimado, no debe chequear la lista de tareas de este issue a mano, las mismas se chequearan a medida que la catedra vaya cerrando los PR!
