### ISSUE TITLE
TP1 - PascalFC - Paredes

### ISSUE THREAD

**Issue by fivanparedes** [PYLP-UNaM/PYLP#674]
- [x] #668 
- [x] #669 
- [x] #670
- [x] #734  
- [x] #735

**Comment by SuichiM** [comment]
recorda asignarle tambien el label epic a estos issues que engloban los ejercicios de un TP

**Comment by fivanparedes** [comment]
> recorda asignarle tambien el label epic a estos issues que engloban los ejercicios de un TP

En los lineamientos decía que el label lo aplica el personal de la cátedra, pero bien, gracias por el feedback.

**Comment by SuichiM** [comment]
Te animas a enviar un PR eliminando esa línea de los lineamientos? Sobre main directamente!

**Comment by fivanparedes** [comment]
Lo haré.
